import React from 'react';

const Home = () => {
  return (
    <div className="container my-5">
      <div className="jumbotron text-center bg-light mb-4">
        <h1 className="display-4">Welcome to Interdimensional Comedy</h1>
        <p className="lead">Generate hilarious comedy shows with AI!</p>
      </div>
      <div className="row">
        <div className="col-md-4">
          <div className="card mb-4">
            <img src="https://via.placeholder.com/150" className="card-img-top" alt="Comedy 1" />
            <div className="card-body">
              <h5 className="card-title">AI Stand-Up Comedy</h5>
              <p className="card-text">Experience hilarious stand-up comedy generated by AI.</p>
              <a href="/generate-comedy" className="btn btn-dark">Generate Now</a>
            </div>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card mb-4">
            <img src="https://via.placeholder.com/150" className="card-img-top" alt="Comedy 2" />
            <div className="card-body">
              <h5 className="card-title">AI Sketch Comedy</h5>
              <p className="card-text">Create sketch comedy that’s out of this world with AI.</p>
              <a href="/generate-comedy" className="btn btn-dark">Generate Now</a>
            </div>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card mb-4">
            <img src="https://via.placeholder.com/150" className="card-img-top" alt="Comedy 3" />
            <div className="card-body">
              <h5 className="card-title">Interdimensional Comedy Show</h5>
              <p className="card-text">Tune into comedy shows from different dimensions.</p>
              <a href="/generate-comedy" className="btn btn-dark">Generate Now</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
